#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

YELLOW='\033[0;33m'       # Yellow
NC='\033[0m' # No Color


echo \"${YELLOW}...............................\";
echo \"4. Checking UNIT TESTS\";
echo \"...............................${NC}\";
CI=true npm run test:unit
echo \"${YELLOW}UNIT TESTS OK${NC} ✅\";
echo \"...............................\";
echo \ 
echo \ 